### ISSUE TITLE
`networkId=custom-network` does not work with direct link

### ISSUE THREAD

**Issue by peterwht** [polkadot-api/papi-console#24]
<img width="814" alt="Screenshot 2024-12-18 at 1 46 48 PM" src="https://github.com/user-attachments/assets/f54528ad-fc26-4d04-9534-6047d04f9a8e" />

When using the custom-network `networkId`, dev.papi.how does not read the URL data and defaults to the Polkadot Relay chain.

This is **not** talking about this flow:
1. dev.papi.how
2. Switch Network
3. Custom URL

Instead it is when a prebuilt link is used to access a specific chain using the PAPI console.

This link allows you to re-create the issue: https://dev.papi.how/explorer#networkId=custom-network&endpoint=wss://rpc1.paseo.popnetwork.xyz. This will show blocks for Polkadot, not Pop Network.

With `networkId=localhost` it does actually work (regardless of localhost or not)
https://dev.papi.how/explorer#networkId=localhost&endpoint=wss://rpc1.paseo.popnetwork.xyz.

**Comment by josepot** [comment]
Thanks for reporting this issue! It's fixed now... The only thing to keep in mind is that now the URIs for custom networks look like this:
https://dev.papi.how/explorer#networkId=custom&endpoint=wss://rpc1.paseo.popnetwork.xyz
